### ISSUE TITLE
RubyGems 레포지터리에 등록하기

### ISSUE THREAD

**Issue by BenjaminKim** [kakao/credit-card-sms-parser#1]

**Comment by probepark** [comment]
왜 한글인건가요

**Comment by BenjaminKim** [comment]
@probepark 왜냐면 이 프로젝트는 한국 신용카드사 sms 만 파싱할꺼니깐. 글로벌화 계획이 없어서 이슈나 설명글도 다 한글로 할 생각이에요. 하하.

**Comment by BenjaminKim** [comment]
[등록완료](https://rubygems.org/gems/credit-card-sms-parser)

**Comment by probepark** [comment]
오
 ㅋㅋ 굿잡
